name = "battleship-p2p"
main = "worker.js"
compatibility_date = "2023-12-01"

[env.production]
name = "battleship-p2p"
routes = [
  { pattern = "battleship-p2p.your-subdomain.workers.dev/*", zone_name = "your-domain.com" }
]

# For custom domain (optional)
# [env.production]
# name = "battleship-p2p-prod"
# route = { pattern = "battleship.your-domain.com/*", zone_name = "your-domain.com" }

# Environment variables (if needed)
# [vars]
# ENVIRONMENT = "production" 