name = "battleship-p2p"

compatibility_date = "2023-07-01"

send_metrics = false
pages_build_output_dir = "dist"

[dev]
local_protocol = "http"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "ROOMS"
id = "ba4234ab6d294162bdc6bfd4f4a9a4b1"

[[kv_namespaces]]
binding = "MESSAGES"
id = "a20d404987fa402bbd0c155b4fb139e2"
