name = "battleship-p2p"

compatibility_date = "2023-07-01"

send_metrics = false

# Worker entry for Durable Object signaling
main = "src/worker.js"

[dev]
local_protocol = "http"

# Durable Object binding for room coordination
[durable_objects]
bindings = [
  { name = "ROOM_DO", class_name = "RoomDurable" }
]

[[migrations]]
tag = "v1-room-do"
new_classes = ["RoomDurable"]

# Static assets (Pages build output) served from Worker
[assets]
directory = "dist"
binding = "STATIC_ASSETS"
